# Generated by Django 5.0.6 on 2024-06-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('Inspirational', 'Inspirational'), ('Motivational', 'Motivational'), ('General', 'General'), ('Love', 'Love'), ('Humor', 'Humor'), ('Philosophy', 'Philosophy'), ('Science', 'Science'), ('Technology', 'Technology'), ('Programming', 'Programming'), ('Business', 'Business'), ('Leadership', 'Leadership'), ('Success', 'Success'), ('Life', 'Life'), ('Friendship', 'Friendship'), ('Wisdom', 'Wisdom'), ('Education', 'Education'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Sports', 'Sports'), ('Music', 'Music'), ('Movies', 'Movies'), ('Art', 'Art'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Nature', 'Nature'), ('Environment', 'Environment'), ('Politics', 'Politics'), ('Economics', 'Economics'), ('History', 'History'), ('Religion', 'Religion'), ('Spirituality', 'Spirituality'), ('Psychology', 'Psychology'), ('Self-Help', 'Self-Help'), ('Relationships', 'Relationships'), ('Parenting', 'Parenting'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Children', 'Children'), ('Teens', 'Teens'), ('Seniors', 'Seniors'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
